version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "*"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    exclude-paths:
      - "*"
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
