#!/bin/bash
# Just in case

declare -a small=("blood-rush")

declare -a themes=(
  "80s-neon"
  "abate"
  "abecedarium"
  "absolutegruv"
  "abyssal"
  "adrenaline"
  "adwaita"
  "agate"
  "aged-whisky"
  "al-dente"
  "allium"
  "amoled-serenity"
  "anuppuccin"
  "apatheia"
  "apex"
  "arcane"
  "arzaba"
  "atom"
  "atomus"
  "aura-dark"
  "aura"
  "aurora-twilight"
  "aurora"
  "autotape"
  "avatar"
  "ayu-light-mirage"
  "ayu-mirage"
  "azure"
  "base2tone"
  "baseline"
  "behave-dark"
  "big-bold"
  "black"
  "blackbird"
  "blood-rush"
  "blossom"
  "blue-topaz"
  "bolt"
  "border"
  "borealis"
  "bossidian"
  "brainhack"
  "brutalism"
  "buena-vista"
  "carbon"
  "cardstock"
  "catppuccin"
  "celestial-night"
  "charcoal"
  "chiaroscuroflow"
  "chime"
  "christmas"
  "cobalt-peacock"
  "cocoa"
  "coffee"
  "colored-candy"
  "comfort-color-dark"
  "comfort-dark"
  "comfort-smooth"
  "comfort"
  "composer"
  "consolas"
  "covert"
  "creature"
  "creme-brulee"
  "cupertino"
  "cyber-glow"
  "cybertron-shifted"
  "cybertron"
  "dark-castle"
  "dark-clarity"
  "dark-graphite-pie"
  "dark-graphite"
  "dark-moss"
  "darkember"
  "darkyan"
  "dashboard"
  "dawn"
  "dayspring"
  "deeper-work"
  "default"
  "dekurai"
  "discordian"
  "dracula-for-obsidian"
  "dracula-gemini"
  "dracula-lyt"
  "dracula-official"
  "dracula-plus"
  "dracula-slim"
  "duality"
  "dune"
  "dunite"
  "dynamic-color"
  "ebullientworks"
  "eldritch"
  "elegance"
  "emerald-echo"
  "encore"
  "ethereon"
  "evangelion"
  "everblush"
  "everforest-enchanted"
  "everforest-spruce"
  "evergreen-shadow"
  "evilred"
  "faded"
  "fancy-a-story"
  "fastppuccin"
  "feather"
  "firefly"
  "flatcap"
  "flexcyon"
  "flexoki-warm"
  "flexoki"
  "focus"
  "frost"
  "fusion"
  "future"
  "garden-gnome-adwaita-gtk"
  "gdct-dark"
  "gdct"
  "github-theme"
  "githubdhc"
  "gitsidian"
  "glass-robo"
  "golden-topaz"
  "green-nightmare"
  "gummy-revived"
  "hackthebox"
  "halcyon"
  "heboric"
  "hipstersmoothie"
  "hulk"
  "ia-writer"
  "ib-writer"
  "iceberg"
  "improved-potato"
  "ink"
  "ion"
  "iridium"
  "its-theme"
  "jotter"
  "kakano"
  "kanagawa-paper"
  "kanagawa"
  "kiwi-mono"
  "kurokula"
  "lagom"
  "latex"
  "lavender-mist"
  "lemons-theme"
  "lesswrong"
  "light-bright"
  "listive"
  "lorens"
  "lumines"
  "lyt-mode"
  "mado-11"
  "mado-miniflow"
  "magicuser"
  "mammoth"
  "maple"
  "material-3"
  "material-flat"
  "material-gruvbox"
  "material-ocean"
  "matrix"
  "meridian"
  "micro-mike"
  "midnight-fjord"
  "midnight"
  "minimal-dark-coder"
  "minimal-dracula"
  "minimal-edge"
  "minimal-red"
  "minimal-resources"
  "minimalists-paradise"
  "mint-breeze"
  "mistymauve"
  "modern-genz-vibedose"
  "mono-black-monochrome-charcoal"
  "monochroyou"
  "monokai"
  "moonlight"
  "mulled-wine"
  "mushin"
  "muted-blue"
  "nebula"
  "neo"
  "neon-synthwave"
  "neovim"
  "neuborder"
  "neutral-academia"
  "nier"
  "nightfox"
  "nightingale"
  "nobb"
  "noctilux"
  "noctis"
  "nord"
  "nordic"
  "northern-sky"
  "nostromo"
  "nota-limonada-light"
  "notation"
  "notation-2"
  "notation"
  "notswift"
  "novadust"
  "obsidian-boom"
  "obsidian-gruvbox"
  "obsidian-nord"
  "obsidian_ia"
  "obsidian_vibrant"
  "obsidianite"
  "obsidianotion"
  "obuntu"
  "oistnb"
  "old-world"
  "oldsidian-purple"
  "oledblack"
  "oliviers-theme"
  "omega"
  "onenice"
  "ono-sendai"
  "orange"
  "oreo"
  "origami"
  "origin"
  "osaka-jade"
  "overcast"
  "pale"
  "panic-mode"
  "penumbra"
  "perso"
  "phoenix"
  "pine-forest-berry"
  "pink-topaz"
  "pisum"
  "playground"
  "pln"
  "poimandres"
  "poimandres-extended"
  "polka"
  "pomme-notes"
  "powered-by-lancer"
  "powered-by-lancer-retouched"
  "primary"
  "prime"
  "prism"
  "proper-dark"
  "protocolblue"
  "prussian-blue"
  "pure"
  "purple-aurora"
  "purple-owl"
  "pxld"
  "qlean"
  "quillcode"
  "radiance"
  "ravenloft"
  "red-graphite"
  "red-shadow"
  "redshift-oled-blue-light-filter"
  "refined-default"
  "reshi"
  "retro-windows"
  "retroma"
  "retronotes"
  "reverie"
  "rezin"
  "rift"
  "rmaki"
  "robsi"
  "rose-pine"
  "rose-pine-2"
  "rose-pine-moon"
  "rose-pine-2"
  "rose-pine"
  "rose-red"
  "royal-velvet"
  "sad-machine-druid"
  "sakurajima"
  "salem"
  "sanctum-reborn"
  "sanctum"
  "sandover"
  "sandstorm"
  "sanguine"
  "sea-glass"
  "seamless-view"
  "sei"
  "serenity"
  "serif"
  "serika"
  "shade-sanctuary"
  "shadeflow"
  "shiba-inu"
  "shimmering-focus"
  "simple-color"
  "simple"
  "simplicity"
  "simply-colorful"
  "sodalite"
  "solarized"
  "solitude"
  "soloing"
  "soothe"
  "space"
  "sparkling-day"
  "sparkling-night"
  "sparkling-wisdom"
  "spectrum-blue"
  "spectrumplus"
  "spring"
  "spy-terminal"
  "sqdthone"
  "strict"
  "subtlegold"
  "suddha"
  "sunbather"
  "synthwave-84"
  "synthwave"
  "terminal"
  "theme-that-shall-not-be-named"
  "things-3"
  "things"
  "tiniri"
  "tokyo-night"
  "tokyo-night-simple"
  "tokyo-night-storm"
  "tokyo-night"
  "tomorrow-night-bright"
  "tomorrow"
  "toms-theme"
  "trace-labs"
  "transient"
  "transparent"
  "typewriter"
  "typomagical"
  "typora-vue"
  "tyrone-neon"
  "ukiyo"
  "ultra-lobster"
  "underwater"
  "ursa"
  "vanilla-amoled-color"
  "vanilla-amoled"
  "vanilla-palettes"
  "vauxhall"
  "velocity"
  "velvet-moon"
  "venom"
  "vercel-geist"
  "vesnea-vibe"
  "vesper"
  "vibrant"
  "vicious"
  "violet-evening"
  "virgo"
  "vortex"
  "w95"
  "wasp"
  "wikipedia"
  "wilcoxone"
  "willemstad"
  "winter-spices"
  "wiselight"
  "wombat"
  "wy-console"
  "wyrd"
  "yue"
  "zario"
  "zen"
  "zenburn"

)

cd ..
mkdir temp
cd temp

#for i in "${small[@]}"; do
for i in "${themes[@]}"; do
  echo "Start ${i}"
  git clone git@github.com:quartz-themes/${i}.git
  cd ${i}
  # git config pull.rebase >&- || git config pull.rebase false
  git config --local pull.rebase false
  git config remote.template.url >&- || git remote add template git@github.com:quartz-themes/quartz-themes-preview-template.git
  git pull template v4 -X theirs --no-edit || git pull template v4 -X theirs --allow-unrelated-histories --no-edit
  git pull origin v4 -X theirs --no-edit || git pull origin v4 -X theirs --allow-unrelated-histories --no-edit
  # rm .github/workflows/deploy-preview.yml
  # rm .github/workflows/update.yml

  # rm -rf quartz/i18n/*
  # cp -r ../../templater/quartz/i18n/* quartz/i18n/

  git commit -a -m "Updated to latest template."

  # replace pageTitle: "Quartz 4", with pageTitle: "${i}", in `quartz.config.ts`
  sed -e 's|pageTitle: "Quartz 4"|pageTitle: "'${i}'"|' -i "" quartz.config.ts

  # replace baseUrl: "quartz.jzhao.xyz", with baseUrl: "quartz-themes.github.io/${i}", in `quartz.config.ts`
  sed -e 's|baseUrl: "quartz.jzhao.xyz"|baseUrl: "quartz-themes.github.io/'${i}'"|' -i "" quartz.config.ts

  # replace ---.*?Quartz is a fast, with ---\n\nQuartz is a fase, in `docs/index.md` using perl
  # perl -0777 -i -pe 's/\n---.*?Quartz is a fast/\n---\n\nQuartz is a fast/' docs/index.md

  # replace Quartz is a fast with [${i}](https://github.com/quartz-themes/${i})\n\nQuartz is a fast, in `docs/index.md`
  # sed -i -e 's|Quartz is a fast|[Quartz Themes on GitHub](https://github.com/saberzero1/quartz-themes/tree/master/themes/'${i}').\n\nQuartz is a fast|' docs/index.md

  git commit -a -m "Applied overrides to template."

  git push || git push --force
  # git push
  cd ..
  echo "Finished ${i}"
done

cd ..
rm -rf temp
cd templater
