name: Deploy Quartz Themes preview to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "40 */4 * * *"
  push:
    branches:
      - v5

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.repository != 'quartz-themes/quartz-themes-preview-template' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      # - name: Cache dependencies
      #   uses: actions/cache@v5
      #   with:
      #     path: ~/.npm
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-
      #
      - name: Cache Quartz plugins
        uses: actions/cache@v5
        with:
          path: .quartz/plugins
          key: ${{ runner.os }}-plugins-${{ hashFiles('quartz.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-plugins-

      - name: Install updates
        uses: nick-fields/retry@v3
        with:
          command: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            npm install
            npx quartz upgrade
            npx quartz plugin restore
            npx quartz plugin update
            git push
          timeout_minutes: 3
          max_attempts: 3

      - name: Build Quartz Docs
        uses: nick-fields/retry@v3
        with:
          command: npx quartz build -d docs
          timeout_minutes: 5
          max_attempts: 3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
